#%RAML 1.0 DataType
type: object
properties:
  cid:
    type: string
  applicantName:
    type: string
    required: true
  dateOfApplication:
    type: date-only
  jobId:
    type: string
  applicantType:
    type: !include ApplicantType.raml
  applicationStatus:
    type: !include ApplicationStatus.raml
  onlineTestStatus:
    type: !include OnlineTestStatus.raml
  onlineTestEvaluation:
    type: string
  score:
    type: integer
  locationPreference1:
    type: string
  locationPreference2:
    type: string
  contactNumber:
    type: string
  emailId:
    type: string
  currentLocation:
    type: string
  qualification:
    type: string
  collegeName:
    type: string
  passoutYear: integer
  programmingSkills: string
  experience: integer
  designation: string
  expInCC: integer
  noticePeriod: number
  openForRelocation: boolean
  currentSalary: number
  expectedSalary: number
  currentRound: 
    type: !include InterviewRound.raml
  interviewPanelist: string
  comments: string
