#%RAML 1.0 NamedExample
value:
  -
    cid: APP001
    applicantName: string1
    dateOfApplication: 2020-10-09
    jobId: JOB001
    applicantType: FRESHER
    applicationStatus: SUBMITTED
    onlineTestStatus: PASS
    onlineTestEvaluation: string
    score: 200
    locationPreference1: string
    locationPreference2: string
    locationPreference3: string
    contactNumber: string
    emailId: string
    currentLocation: string
    qualification: string
    collegeName: string
    passoutYear: 2020
    programmingSkills: string
    experience: 7
    designation: string
    expInCC: 0
    noticePeriod: 60
    openForRelocation: false
    currentSalary: 2020
    expectedSalary: 2020
    currentRound: Technical
    interviewPanelist: string
    comments: string
  -
    cid: APP002
    applicantName: string1
    dateOfApplication: 2020-10-09
    jobId: JOB002
    applicantType: EXPERIENCE
    applicationStatus: ACCEPTED
    onlineTestStatus: FAIL
    onlineTestEvaluation: string
    score: 200
    locationPreference1: string
    locationPreference2: string
    locationPreference3: string
    contactNumber: string
    emailId: string
    currentLocation: string
    qualification: string
    collegeName: string
    passoutYear: 2020
    programmingSkills: string
    experience: 7
    designation: string
    expInCC: 12
    noticePeriod: 60
    openForRelocation: false
    currentSalary: 2020
    expectedSalary: 2020
    currentRound: Manager
    interviewPanelist: string
    comments: string

  