#%RAML 1.0 NamedExample
value:
  -
    employeeId: EMP001
    employeeName: string
    dateofBirth: 2020-09-09
    dateOfJoining: 2020-09-09
    nickName: string
    gender: Male
    country: string
    state: string
    language: string
    email: string
    mobileNumber: "8884234164"
    deptId: DEPT001
    managerId: MGR001
  -
    employeeId: EMP002
    employeeName: string
    dateofBirth: 2020-09-09
    dateOfJoining: 2020-09-09
    nickName: string
    gender: Female
    country: string
    state: string
    language: string
    email: string
    mobileNumber: "8884234164"
    deptId: DEPT002
    managerId: MGR002
